name: Check aiobotocore stubs

on:
  # schedule:
  #   - cron: "0 0 * * *"
  workflow_dispatch: {}

jobs:
  check-aiobotocore-stubs:
    env:
      PIP_NO_CACHE_DIR: false
      PIP_USER: 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install poetry pip
          poetry config virtualenvs.create false
          poetry install -n
      - name: Install aiobotocore
        run: |
          poetry run pip install -U aiobotocore
          poetry install -n
      - name: Uninstall stubs
        run: |
          poetry run pip uninstall -y boto3-stubs botocore-stubs types-aioboto3 types-aiobotocore
      - name: Check aioboto3 stubs
        run: |
          poetry run ./scripts/check_stubs.py -bid aiobotocore
