name: Check aio stubs

on:
  # schedule:
  #   - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      boto3_version:
        description: Target boto3 version
        required: false

jobs:
  check-aio-stubs:
    env:
      PIP_NO_CACHE_DIR: false
      PIP_USER: 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Extract versions
        id: vars
        uses: actions/github-script@v6
        with:
          script: |
            const { extractVersionsFromInput } = require('./.github/workflows/helpers.js')
            await extractVersionsFromInput({ core, context })
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install poetry pip
          poetry config virtualenvs.create false
          poetry install -n
      - name: Install aioboto3
        run: |
          poetry run pip install -U aioboto3
          poetry run pip install -U aiobotocore
          poetry install -n
      - name: Install boto3
        env:
          BOTO3_VERSION: ${{ steps.vars.outputs.boto3-version }}
          BOTOCORE_VERSION: ${{ steps.vars.outputs.botocore-version }}
        run: |
          poetry run pip install -U boto3==${BOTO3_VERSION} botocore==${BOTOCORE_VERSION}
      - name: Uninstall stubs
        run: |
          poetry run pip uninstall -y boto3-stubs botocore-stubs
      - name: Check aio stubs
        run: |
          poetry run istub -c ./istub_aio.yml -bid aioboto3 aiobotocore
