name: boto3-stubs-full integration

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}

jobs:
  integration:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version
      - name: Set up uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"
      - name: Install the project
        run: uv sync --extra check --dev
      - name: Install extras
        run: uv pip install aioboto3
      - name: Build full packages
        run: |
          uv run scripts/build.sh --product boto3 --no-smart-version
          uv run scripts/build.sh --product boto3-full -s s3 ec2 --no-smart-version
          uv run scripts/build.sh --product aioboto3 aiobotocore --no-smart-version
          uv run scripts/build.sh --product aiobotocore-full -s s3 --no-smart-version
      - name: Install full packages
        run: |
          uv run scripts/install.sh master
          uv run scripts/install.sh full
          uv run scripts/install_aiobotocore.sh master
          uv run scripts/install_aiobotocore.sh full
      - name: Integration tests
        run: uv run scripts/integration.py --product boto3 -fd s3 ec2
      - name: Aio integration tests
        run: uv run scripts/integration.py --product aioboto3 -fd s3
