name: types-boto3-custom integration

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}

jobs:
  integration:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version
      - name: Set up uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"
      - name: Integration tests
        run: |
          uv run scripts/integration.py -w --product boto3_custom -d s3 ec2
      - name: Aio integration tests
        run: |
          uv run scripts/integration.py -w --product aioboto3_custom -fd s3
