name: "Integration: All products"

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}

jobs:
  integration:
    name: "Integration: All products"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        product:
          - "types-boto3"
          - "types-boto3-full"
          - "types-boto3-custom"
          - "boto3-stubs"
          - "boto3-stubs-full"
          - "boto3-stubs-custom"
          - "types-aioboto3"
          - "types-aioboto3-full"
          - "types-aioboto3-custom"
          - "types-aiobotocore"
          - "types-aiobotocore-full"
          - "types-aiobotocore-custom"
        python_version:
          - "3.8"
          # - "3.10"
          # - "3.13"
    steps:
      - uses: actions/checkout@v4
      - name: Set up uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"
      - name: types-boto3-full integration tests
        run: |
          uv run scripts/integration.py \
            --product ${{ matrix.product }} \
            --python ${{ matrix.python_version }} \
            -d