name: Code style and test

on:
  push: {}
  workflow_dispatch: {}

jobs:
  unit-tests:
    name: Code style & unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - "3.10"
          - "3.11"
          - "3.12"
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.version }}"
          cache: "poetry"
      - name: Install dependencies
        run: |
          poetry install -n
          poetry run pip install -U --no-dependencies aiobotocore types-aiobotocore
      - name: Lint
        run: |
          poetry run flake8 mypy_boto3_builder
      - name: Formatting
        run: |
          poetry run black --check mypy_boto3_builder tests
          poetry run isort -c mypy_boto3_builder tests
      - run: echo "$(poetry env info --path)/bin" >> $GITHUB_PATH
      - name: Typing
        uses: jakebailey/pyright-action@v1
      - name: Test
        run: |
          poetry run pytest
