name: Generate docs
concurrency:
  group: generate_docs
  cancel-in-progress: true

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch: {}

jobs:
  build-docs:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python for Poetry
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install poetry
        run: |
          python -m pip install poetry pip
          poetry config virtualenvs.create false
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "poetry"
      - name: Install dependencies
        run: |
          poetry install -n
          python -m pip install -U handsdown
          python -m pip install -r requirements.mkdocs.txt
      - name: Build docs
        run: |
          python -m handsdown --external `git config --get remote.origin.url` -o docsmd --cleanup --theme material --branch main $@
          rm -rf docs/*
          python -m mkdocs build
      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: ./gh-pages
      - name: Commit changes
        run: |
          cd ./gh-pages
          git config --global user.email "github-actions"
          git config --global user.name "github-actions@github.com"
          rm -rf docs docsmd
          mv ../docs .
          mv ../docsmd .
          git add docs
          git add docsmd
          git commit -am "Update docs"
          git push
