name: "Test: coverage report"

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  coverage:
    name: "Test: coverage report"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version
      - name: Set up uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"
      - name: Install the project
        run: uv sync --dev
      - name: Build coverage report
        run: uv run pytest --cov mypy_boto3_builder --cov-report=xml --junitxml=junit.xml
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: coverage.xml
