name: Publish types-aioboto3
concurrency: update_types_aioboto3

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      aioboto3_version:
        description: Target aioboto3 version
        required: false
        type: string
        default: ""
      force:
        description: Continue if version is already published
        required: false
        default: false
        type: boolean
      stubs_version:
        description: Specify version explicitly instead of finding it automatically
        required: false
        type: string
        default: ""
      no_smart_version:
        description: Use exact version provided in stubs_version
        required: false
        default: false
        type: boolean

jobs:
  check-aioboto3-version:
    name: Check aioboto3 version
    runs-on: ubuntu-latest
    outputs:
      aioboto3-version: ${{ steps.vars.outputs.aioboto3-version }}
      version: ${{ steps.vars.outputs.version }}
      extra-flags: ${{ steps.vars.outputs.extra-flags }}
    steps:
      - uses: actions/checkout@v3
      - name: Extract versions
        id: vars
        uses: actions/github-script@v6
        with:
          script: |
            const { setupGlobals, extractAioBoto3Versions } = require('./.github/workflows/helpers.js')
            setupGlobals({ core, context, fetch })
            await extractAioBoto3Versions()
  publish-types-aioboto3:
    name: Publish types-aioboto3
    runs-on: ubuntu-latest
    needs: check-aioboto3-version
    if: needs.check-aioboto3-version.outputs.version
    env:
      AIOBOTO3_VERSION: ${{ needs.check-aioboto3-version.outputs.aioboto3-version }}
      VERSION: ${{ needs.check-aioboto3-version.outputs.version }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Get aioboto3 download links
        id: links
        uses: actions/github-script@v6
        with:
          script: |
            const { setupGlobals, extractAioBoto3DownloadLinks } = require('./.github/workflows/helpers.js')
            setupGlobals({ core, context, fetch })
            await extractAioBoto3DownloadLinks()
      - name: Install builder
        run: |
          rm -rf mypy_boto3_builder
          python -m pip install mypy_boto3_builder
      - name: Install aioboto3
        run: |
          mkdir installtemp
          cd installtemp
          wget ${{ steps.links.outputs.aioboto3-url }}
          pip install aioboto3*
          cd ..
          rm -rf installtemp
      - name: Build all packages
        run: |
          rm -rf mypy_boto3_output/*

          echo "Building all packages"
          python -m mypy_boto3_builder mypy_boto3_output -b ${VERSION} --product aioboto3 -s all -d
      - name: Install dependencies for publishing
        run: |
          python -m pip install setuptools wheel twine
      - name: Publish to PyPI
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python ./scripts/release.py
      - name: Store types-aioboto3 artifact
        uses: actions/upload-artifact@v3
        with:
          name: types-aioboto3
          path: mypy_boto3_output/types_aioboto3_package/dist/*.whl
