name: Update types-aiobotocore
concurrency: update_types_aiobotocore

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      aiobotocore_version:
        description: Target aiobotocore version
        required: false
        type: string
      stubs_version:
        description: Specify version explicitly instead of finding it automatically
        required: false
        default: ""
        type: string
      force:
        description: Continue if version is already published
        required: false
        default: false
        type: boolean
      skip_published:
        description: Skip already published packages
        required: false
        default: false
        type: boolean

jobs:
  check-aiobotocore-version:
    name: Check aiobotocore version
    runs-on: ubuntu-latest
    outputs:
      aiobotocore-version: ${{ steps.vars.outputs.aiobotocore-version }}
      version: ${{ steps.vars.outputs.version }}
      extra-flags: ${{ steps.vars.outputs.extra-flags }}
    steps:
      - uses: actions/checkout@v3
      - name: Extract versions
        id: vars
        uses: actions/github-script@v6
        with:
          script: |
            const { extractAioBotocoreVersions } = require('./.github/workflows/helpers.js')
            await extractAioBotocoreVersions({ core, context })
  publish-types-aiobotocore:
    name: Publish types-aiobotocore
    runs-on: ubuntu-latest
    needs: check-aiobotocore-version
    if: needs.check-aiobotocore-version.outputs.version
    env:
      AIOBOTOCORE_VERSION: ${{ needs.check-aiobotocore-version.outputs.aiobotocore-version }}
      VERSION: ${{ needs.check-aiobotocore-version.outputs.version }}
      EXTRA_FLAGS: ${{ needs.check-aiobotocore-version.outputs.extra-flags }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Get aiobotocore download links
        id: links
        uses: actions/github-script@v6
        with:
          script: |
            const { extractAioBotocoreDownloadLinks } = require('./.github/workflows/helpers.js')
            await extractAioBotocoreDownloadLinks({ core })
      - name: Install builder
        run: |
          rm -rf mypy_boto3_builder
          python -m pip install mypy_boto3_builder
      - name: Install aiobotocore
        run: |
          mkdir installtemp
          cd installtemp
          wget ${{ steps.links.outputs.aiobotocore-url }}
          pip install aiobotocore*
          cd ..
          rm -rf installtemp
      - name: Build all packages
        run: |
          rm -rf mypy_boto3_output/*

          echo "Building all packages"
          python -m mypy_boto3_builder mypy_boto3_output -b ${VERSION} --product aiobotocore aiobotocore-services ${EXTRA_FLAGS} -s all
      - name: Install dependencies for publishing
        run: |
          python -m pip install setuptools wheel twine
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python ./scripts/release.py
      - name: Store types-aiobotocore artifact
        uses: actions/upload-artifact@v2
        with:
          name: types-aiobotocore
          path: mypy_boto3_output/types_aiobotocore_package/dist/*.whl
