name: Check stubs

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      boto3_version:
        description: Target boto3 version
        required: false

jobs:
  check-stubs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Extract versions
        id: vars
        uses: actions/github-script@v6
        with:
          script: |
            const { setupGlobals, extractVersionsFromInput } = require('./.github/workflows/helpers.js')
            setupGlobals({ core, context, fetch })
            await extractVersionsFromInput()
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install poetry pip
          poetry config virtualenvs.create false
          poetry install -n
      - name: Install boto3
        env:
          BOTO3_VERSION: ${{ steps.vars.outputs.boto3-version }}
          BOTOCORE_VERSION: ${{ steps.vars.outputs.botocore-version }}
        run: |
          poetry run pip install -U boto3==${BOTO3_VERSION} botocore==${BOTOCORE_VERSION}
          poetry run pip install -U botocore-stubs
      - name: Uninstall stubs
        run: |
          poetry run pip uninstall -y boto3-stubs
      - name: Check boto3 stubs
        run: |
          poetry run istub -c ./istub.yml -bid boto3
